---
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

---
spring:
  profiles: prod

---
spring:
  profiles: test
