eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 6
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
