---
server:
  port: ${DEMO_SERVICE_PORT:8080}

---
spring:
  profiles: prod

demo:
  service:
    username: ali-prod
    password: '{cipher}AQAOgavyazUUlmZ9ckCEL0gFVO4v5/BjnUYhM+yo11lAUirGINtOtTDzHizYRvoayXOCYOz8P30aDuqwl9aTDkyzRocnTK8azIl1f9HXBco49LZ830lftOyy2ciniAkQ8ZoOQJGnnxJ/y5yOYpWhCtcoReOpL/Dd7AbJJ9CeYdTYBOQ56TPmYkwEcfG7R4O1Hr5WhS5j4iAhf3RG13xZKHlfZmB1cyUkG4nVLFHOKMIQCJZGy8TAexxyGHkXroBVP7FBapPmUxafvh8npGdiaQyyefMS91YqWcK/AB1T1Or7+38b1KqUI8Rxi/X93Cfw1p5mlwWoOkDgi7LWLYenJh6M0IdIqeRvG9WgANV/xpIjdv79tcW6Zal4rZdszYg03uE='

---
spring:
  profiles: test

demo:
  service:
    username: ali-test
    password: veli-test
