---
server:
  port: ${DEMO_SERVICE_PORT:8080}

---
spring:
  profiles: prod

demo:
  service:
    username: ali-prod2
    password: veli-prod2

---
spring:
  profiles: test

demo:
  service:
    username: ali-test
    password: veli-test
