---
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
    peerNodeConnectionIdleTimeoutSeconds: 5
    renewalThresholdUpdateIntervalMs: 10000
    peerEurekaStatusRefreshTimeIntervalMs: 10000
    peerEurekaNodesUpdateIntervalMs: 10000
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

---
spring:
  profiles: eureka-peer-1
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: eureka-peer-2
server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
