---
server:
  port: ${SIMPLE_MODULE_PORT:8080}

---
spring:
  profiles: prod

simplemodule:
  username: ali
  password: veli

---
spring:
  profiles: test

simplemodule:
  username: ali-test
  password: veli-test
