---
server:
  port: ${TURBINE_SERVICE_PORT:9999}

turbine:
  amqp:
    port: ${TURBINE_AMQP_PORT:8989}
  aggregator:
    clusterConfig: microservices-cluster
  appConfig: eureka,demo-service,iddaa-service,finance-service,zuul
  clusterNameExpression: "'microservices-cluster'"

---
spring:
  profiles: prod

---
spring:
  profiles: test
